### ISSUE TITLE
[VS] fabric testcase is failing with errors

### ISSUE THREAD

**Issue by lolyu** [sonic-net/sonic-swss#2573] opened 2022-12-15 02:27 UTC
`test_fabric.py::TestVirtualChassis::test_voq_switch` errored in branch 202205:
```
test_fabric.py::TestVirtualChassis::test_voq_switch ERROR                [ 23%]
```

Please refer to this dummy PR for more details: https://github.com/sonic-net/sonic-swss/pull/2566

**Comment by lolyu** [comment] 2022-12-16 05:33
This error is consistently failing on 202205 branch.

**Comment by prsunny** [comment] 2022-12-16 18:06
@arlakshm , can you please take a look? Seems blocking 202205 PRs.

**Comment by judyjoseph** [comment] 2022-12-20 07:54
@lolyu, in your dummy PR: https://github.com/sonic-net/sonic-swss/pull/2566, My observation is that I see that the sonic-swss build is not successful because the dependent the sairedis pkg download is failing. Bellow is the link

https://dev.azure.com/mssonic/build/_build/results?buildId=189338&view=logs&jobId=80130f07-32fc-5c19-809b-35051dcc5ef5&j=80130f07-32fc-5c19-809b-35051dcc5ef5&t=9220db1c-94e3-516e-bb9d-5e982f91f3ea

It fails with the error "##[error]No builds currently exist in the pipeline definition supplied." We need to fix this to get the correct sonic-swss package which will be installed later in docker-sonic-vs which is being build in the pipeline.

**Comment by judyjoseph** [comment] 2022-12-20 19:11
Checked with @xumia , created another issue https://github.com/sonic-net/sonic-sairedis/issues/1178 for @kcudnik to take a look. 

Once this is fixed we should have a sairedis build and a sonic-swss build in 202205, which should should solve this original issue

**Comment by judyjoseph** [comment] 2022-12-30 17:47
Sai has fixed this issue in master https://github.com/sonic-net/sonic-sairedis/pull/1174, Needs to be backported to different branches, adding @yxieca for 202205 branch

**Comment by bingwang-ms** [comment] 2023-01-03 06:10
The issue is fixed by PR https://github.com/sonic-net/sonic-sairedis/pull/1189. Closing this issue

**Closed by bingwang-ms** 2023-01-03 06:10 UTC
Labels: Bug :bug:
